# Generated by Django 6.0 on 2026-01-03 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='houseadvertisement',
            old_name='is_approve',
            new_name='is_approved',
        ),
    ]
