# Generated by Django 6.0 on 2026-01-05 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_rename_is_approve_houseadvertisement_is_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='houseimage',
            old_name='house',
            new_name='advertisement',
        ),
        migrations.AlterField(
            model_name='favorite',
            name='advertisement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='rentals.houseadvertisement'),
        ),
        migrations.AlterField(
            model_name='review',
            name='advertisement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='rentals.houseadvertisement'),
        ),
    ]
