# Generated by Django 6.0 on 2026-01-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_rename_house_houseimage_advertisement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseadvertisement',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
